name: AWS Code Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: chrislennon/action-aws-cli@v1.1

    - name: Set AWS region
      run: aws configure set region 【AWSのリージョン】　※東京なら"ap-northeast-1"

    - name: Run AWS CodeDeploy
      run: aws deploy create-deployment --application-name "【CodeDeployで作成したアプリケーション名】" --deployment-group-name "【CodeDeployで作成したデプロイグループ名】" --github-location repository="【GitHubアカウント名/デプロイ対象レポジトリ名】",commitId="${{ github.sha }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
